[gcp_service_account]
type = "service_account"
project_id = "long-leaf-476716-a9"
private_key_id = "3aa8210d988707bd8b94f7f31c2c3fa62aff043a"

# REPARA AQUI: usamos ''' ... ''' para aceitar m√∫ltiplas linhas
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZ4sjnB6btZ8TP
Nqn0oeTLmN0bRecRVgMtc3oYXH+OhTDODuWaZvQ1NdNH5xuo+igG0oySe2AJgHuI
GE6tUd3jOvXnSw5PZW4HTeKeAPzUGiJDT49eYhtsAJd29d/pKkH22FCP5uiRpWfU
WPqujfFBezaY1P503WsTUzmrUuHhmTAz+z5RKm6Cm9gxdqMhThD4N/xeQ/tz8Hqx
+Y/p9LWG75uJMSYIITcH5oF/hTDTKsyx1cLb49pDpIO5PFCpv7p3tOsakU6BE5Q0
0r8Df71N1CI9d86eRitwdTV26qmGvBuN+MneGs7voC+9UBd7g1E3Ni6/w6wCtv28
f6yvAnqTAgMBAAECggEAKmk0UWfse5WTykAYixFrSylwFqonSsHX0lj3F2u2xAK1
NrUoVmt1dozFFBX/q4x2J5szntNd3oCIizOXy3C6pHuFdh9bbEpaDq1KfZ1sENC7
DK4Kp0qGoDdxhxmwgkRhNbTcTyymgC2D9iQnwp/gE9nvbCOXlYHIluTjCfKnylLN
9df+gupjsXBO3kxYEY1MHRSMOvUw5DU+56BpG+3hxs6x9YdcSY/GxdgF661+FNQp
1S1rGAyFV2DnIxiJNCS3K2PXds8O9k0BYExfT4qTz55c5/uz00pAelyU1Fl8dXfR
2IacuxjssI7pDVsvO1wKBfT1xkvTdi03AhO8++k5sQKBgQDZnn1+NfEWiombdmkN
ieLsdv8njt9GMSQGrfuHATqjYCloVVtMQdlrZMZ+EHn/6d8Pa/8jB/JWkfmvkhlQ
ROhbJ/cigrqKhyr63KRSGAx/B5tr+4mjju9u5XYcTl+tEuhzqtaVWisSm+sH+Npl
lbXYUSrDemoTkIpubbiG3loOnwKBgQC1BrzCpQiM1pf5HW159G7yIIzN5ohXlVBy
0ArWTiM94Xzpo6xTQYDL0AsgCjjyO2J+EZsXmcf+uHeSBRGJIRf0wR0+Vibnuwks
jy1+3U6D1admFn6RzZK4vFyRtEKFLxTyvwqo05FJgFwJ25Ze1XT0NQ/CiGyXXmgg
w+V2uMlzjQKBgQCqWQM5GbaIA5gmJrGjVG1a1udyqsciJfNieyyqiI7DNtITBsX5
0o4EIBW0tucZKZRfeRV18ZGErK37/mxsRhRwzr8It7aYG6jMSI0kagjWIzlJdNRQ
QOIyN9KV48/HJkbpzDA/Jx8SaRS439btsBxxoU/NRvTkLb//I0pP4Jw0VwKBgCOv
U1BvZfMVblneMjGDPMegIQGJu0DAn14yoqBCQPI22//WkubKl9AVj8veGAGwMSc2
40LQvrr4tCFlvGIy0t0doF0kcIDnvtQ42TgT+iFE4b3fG040nwKppvnV9fL5KAD+
JeTH5/D8S6hp0AebvnVRbGzlpbplEtO6qiYwIQ4VAoGAZ2mEWFoIVIvuH4/vGMFY
XcIg0eaHRWrbk9qJ87hb8y8LIVlpZOenZuAeagkFhsuToUk9LPzu6pOBltRQls8e
2f2sM7eHtqamNMf1CBhQNgA1aCOjWjdb2t0M/vc+6e45v/yJFyubdD78cS71Sden
94J0igXkYLZn3Y9Ny5QeYbg=
-----END PRIVATE KEY-----
'''

client_email = "controle-de-luvas@long-leaf-476716-a9.iam.gserviceaccount.com"
client_id = "102709051536506920979"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/controle-de-luvas%40long-leaf-476716-a9.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
